### ISSUE TITLE
Grid switch explodes when a 13kv / 60 Kw power src from T1 poles is connected when i open it.

### ISSUE THREAD

**Issue by Electricianfromhell** [jrddunbr/ElectricalAge#250] opened 2021-01-23 04:23 UTC
Grid switch explodes when i try to connect a 13kv power src to it from T1 poles when i open it.

how to reproduce

1. setup banks (a strip of 30 2x2 rotating panels each) of solar panels so it totals about 60,000 Kw on 14 kv T1 Lines with the solar panels running at 4 Kv into the t1 lines per bank.
2. run power lines from t1 poles to grid switch running the 14 Kv / 60 Kw power through it.
3. power and place control button on grid switch.
4. Push button to open switch!
5. BOOM!!!

**Comment by jrddunbr** [comment] 2021-01-23 14:41
Duplicate of #246

**Closed** 2021-01-23 14:42 UTC
