### ISSUE TITLE
Two New Items: Transfer Switches (Manual and Automatic)

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [jrddunbr/ElectricalAge#172] opened 2019-08-01 17:41 UTC
Another two New Items for the pole update i forgot: Transfer Switches (Manual and Automatic)

A transfer switch is a device that is installed after the meter and before the panel that is used to hook up a generator to someones house that disconnects the connection to the grid when the generator comes on when the power goes out to prevent power from the generator going back up to the grid transformer and getting stepped up and going into the grid either frying someone working on the lines or blowing up the generator from the inrush current to the grid due to the amount of inductance the grid has on it.

A Electrical age transfer switch should be able to run power from the grid into someones house and have a slot on the side for another wire to hook up to run power in from a generator or alternate source of power and when power from the grid fails, the transfer switch should activate and sort of like a relay reroute power in from the generator or alternate power source to the home it is installed on.

The Manual transfer switch would have to be manually activated to receive power from the generator

The automatic transfer switch would automatically switch when power coming in from the grid dropped below a preset voltage and would reroute power into the home from a generator. Also it could start a generator connected to it because some TS do that in real life.

**Comment by jrddunbr** [comment] 2019-08-01 18:01
Duplicate of #73

**Closed by jrddunbr** 2019-08-01 18:01 UTC

**Comment by ellingtonvengaboysmuseum** [comment] 2019-08-01 18:06
@jrddunbr - the transfer switch i am talking about for a residential home is not referenced in #73

**Comment by jrddunbr** [comment] 2019-08-01 19:01
It's basically the same concept. I'm trying to to have a million issues for the same update.

**Comment by ellingtonvengaboysmuseum** [comment] 2019-08-01 19:39
ok
