### ISSUE TITLE
Opposing inductors within the same block should share inductance

### ISSUE THREAD

**Issue by Grissess** [jrddunbr/ElectricalAge#46] opened 2018-08-19 18:30 UTC
For performance reasons, this can't superimpose everything, but opposing in the same block shouldn't be hard.

The hard questions are:
- Polarity: probably assume they have the same polarity, so the induced voltage signs are the same.
- Equivalent circuit: inductance from the (assumed) magnetic field is probably best modelled as a current source, with practical limits (in real materials, the currents will eddy out instead of inducing an infinite voltage on an open circuit, for example).
- Other physical parameters: Minecraft blocks are ~1m on each side. This makes the inductors (and most devices in this mod) abnormally large, and also threatens loss of efficiency due to distance. As the inductors have their own core, should they assume to be "conducting" the same H field? How much leakage should occur?

If the math can be worked out, the implementation itself should be surprisingly easy.

**Comment by OmegaHaxors** [comment] 2018-08-19 18:51
For the first point it should run in the opposite direction of the current going through the primary, to make things easier to program and communicate, the inductor should have implicit directionality. The model may have to be tweaked to communicate the 'forward' direction. A disconnected secondary should be completely ignored, as if it didn't exist. A secondary that is shorted should accept any change of flux and convert it into a current source and thus a voltage based on the resistance of the circuit. A shorted secondary is a great tool to avoid ringing from inductor->capacitor interactions or to hold a current from a disconnected primary until it is ready to be used.

Here's where things get interesting. The ratio of how much power is transferred to the other block is based on the ratio of inductance between them. This would work very similarly to a transformer (since it's the same working principle) where a 10H to 1H system would convert a higher power into a lesser one at a rate of 10:1. This would be especially useful for converting a high current surge from a failing primary into an easier to manage high voltage.

Potential for an optional 'core' block to place onto inductors that would make this interaction more efficient, but ideally it should be lossless or as close to lossless as the math will allow.

**Comment by jrddunbr** [comment] 2020-01-07 02:33
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.

**Closed by jrddunbr** 2020-01-07 02:33 UTC
Labels: 1.12, enhancement
