### ISSUE TITLE
Creative Current or Power sources

### ISSUE THREAD

**Issue by Electricianfromhell** [jrddunbr/ElectricalAge#177] opened 2019-08-01 21:41 UTC
Add a amperage input to the Electrical Source item gui to give the ability to set the max Amperage a creative Electrical Source can provide

this would be very useful for testing how breakers react to short circuits with a limited max amperage and finding bugs in Electrical age.

**Comment by jrddunbr** [comment] 2019-08-02 01:42
This is actually called a current or power source. I can't remember which.

**Comment by GrimmDemon** [comment] 2019-08-02 20:49
I somewhat agree with this one. The power output from a creative power source is unlimited, and hard to control if you don't exactly know what you're doing, like myself. when I just to experiment with stuff, without involving my main power generation system, fearing it exploding, this is a real teeth grinder. It would be awesome if the diodes restricted currents above their rated amount instead of melting, but that's not how they work in real life, irl, they do get hot and will explode if too much current is passed through, personal experience here when I tried to make my own bridge rectifier for a high power amplifier, it wasn't fun being struck by boiling hot pieces of plastic.
On that note too, the current maximum diode limit will be insufficient for the new current based cables, even for the low and medium current cables, they need a refresh in my opinion.

**Comment by jrddunbr** [comment] 2019-08-03 22:39
So I do plan to add ideal current sources and ideal power sources. Basically, you enter a number and it outputs that current/power (at maximum).

Diodes will probably get a 75A current tier but that's not a big focus right now.

**Comment by jrddunbr** [comment] 2020-01-07 02:38
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.

**Comment by jrddunbr** [comment] 2020-12-28 14:28
Current sources were added to the game and will be in the next release.

**Closed by jrddunbr** 2020-12-28 14:28 UTC
Labels: enhancement, texture work
